/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnderstandingRouteImport } from './routes/understanding'
import { Route as StakeholdersRouteImport } from './routes/stakeholders'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UnderstandingRoute = UnderstandingRouteImport.update({
  id: '/understanding',
  path: '/understanding',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholdersRoute = StakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/reporting': typeof ReportingRoute
  '/resources': typeof ResourcesRoute
  '/stakeholders': typeof StakeholdersRoute
  '/understanding': typeof UnderstandingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/reporting': typeof ReportingRoute
  '/resources': typeof ResourcesRoute
  '/stakeholders': typeof StakeholdersRoute
  '/understanding': typeof UnderstandingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/reporting': typeof ReportingRoute
  '/resources': typeof ResourcesRoute
  '/stakeholders': typeof StakeholdersRoute
  '/understanding': typeof UnderstandingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/glossary'
    | '/reporting'
    | '/resources'
    | '/stakeholders'
    | '/understanding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/glossary'
    | '/reporting'
    | '/resources'
    | '/stakeholders'
    | '/understanding'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/glossary'
    | '/reporting'
    | '/resources'
    | '/stakeholders'
    | '/understanding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GlossaryRoute: typeof GlossaryRoute
  ReportingRoute: typeof ReportingRoute
  ResourcesRoute: typeof ResourcesRoute
  StakeholdersRoute: typeof StakeholdersRoute
  UnderstandingRoute: typeof UnderstandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/understanding': {
      id: '/understanding'
      path: '/understanding'
      fullPath: '/understanding'
      preLoaderRoute: typeof UnderstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholders': {
      id: '/stakeholders'
      path: '/stakeholders'
      fullPath: '/stakeholders'
      preLoaderRoute: typeof StakeholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GlossaryRoute: GlossaryRoute,
  ReportingRoute: ReportingRoute,
  ResourcesRoute: ResourcesRoute,
  StakeholdersRoute: StakeholdersRoute,
  UnderstandingRoute: UnderstandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
