/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnderstandingRouteImport } from './routes/understanding'
import { Route as StakeholdersRouteImport } from './routes/stakeholders'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/Admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnderstandingIndexRouteImport } from './routes/understanding/index'
import { Route as UnderstandingProceduresRouteImport } from './routes/understanding/procedures'
import { Route as UnderstandingMisconductRouteImport } from './routes/understanding/misconduct'
import { Route as UnderstandingConsentRouteImport } from './routes/understanding/consent'
import { Route as UnderstandingBystanderRouteImport } from './routes/understanding/bystander'

const UnderstandingRoute = UnderstandingRouteImport.update({
  id: '/understanding',
  path: '/understanding',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholdersRoute = StakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/Admin',
  path: '/Admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderstandingIndexRoute = UnderstandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnderstandingRoute,
} as any)
const UnderstandingProceduresRoute = UnderstandingProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => UnderstandingRoute,
} as any)
const UnderstandingMisconductRoute = UnderstandingMisconductRouteImport.update({
  id: '/misconduct',
  path: '/misconduct',
  getParentRoute: () => UnderstandingRoute,
} as any)
const UnderstandingConsentRoute = UnderstandingConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => UnderstandingRoute,
} as any)
const UnderstandingBystanderRoute = UnderstandingBystanderRouteImport.update({
  id: '/bystander',
  path: '/bystander',
  getParentRoute: () => UnderstandingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Admin': typeof AdminRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/quiz': typeof QuizRoute
  '/reporting': typeof ReportingRoute
  '/resources': typeof ResourcesRoute
  '/stakeholders': typeof StakeholdersRoute
  '/understanding': typeof UnderstandingRouteWithChildren
  '/understanding/bystander': typeof UnderstandingBystanderRoute
  '/understanding/consent': typeof UnderstandingConsentRoute
  '/understanding/misconduct': typeof UnderstandingMisconductRoute
  '/understanding/procedures': typeof UnderstandingProceduresRoute
  '/understanding/': typeof UnderstandingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Admin': typeof AdminRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/quiz': typeof QuizRoute
  '/reporting': typeof ReportingRoute
  '/resources': typeof ResourcesRoute
  '/stakeholders': typeof StakeholdersRoute
  '/understanding/bystander': typeof UnderstandingBystanderRoute
  '/understanding/consent': typeof UnderstandingConsentRoute
  '/understanding/misconduct': typeof UnderstandingMisconductRoute
  '/understanding/procedures': typeof UnderstandingProceduresRoute
  '/understanding': typeof UnderstandingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Admin': typeof AdminRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/quiz': typeof QuizRoute
  '/reporting': typeof ReportingRoute
  '/resources': typeof ResourcesRoute
  '/stakeholders': typeof StakeholdersRoute
  '/understanding': typeof UnderstandingRouteWithChildren
  '/understanding/bystander': typeof UnderstandingBystanderRoute
  '/understanding/consent': typeof UnderstandingConsentRoute
  '/understanding/misconduct': typeof UnderstandingMisconductRoute
  '/understanding/procedures': typeof UnderstandingProceduresRoute
  '/understanding/': typeof UnderstandingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Admin'
    | '/about'
    | '/contact'
    | '/faq'
    | '/glossary'
    | '/quiz'
    | '/reporting'
    | '/resources'
    | '/stakeholders'
    | '/understanding'
    | '/understanding/bystander'
    | '/understanding/consent'
    | '/understanding/misconduct'
    | '/understanding/procedures'
    | '/understanding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Admin'
    | '/about'
    | '/contact'
    | '/faq'
    | '/glossary'
    | '/quiz'
    | '/reporting'
    | '/resources'
    | '/stakeholders'
    | '/understanding/bystander'
    | '/understanding/consent'
    | '/understanding/misconduct'
    | '/understanding/procedures'
    | '/understanding'
  id:
    | '__root__'
    | '/'
    | '/Admin'
    | '/about'
    | '/contact'
    | '/faq'
    | '/glossary'
    | '/quiz'
    | '/reporting'
    | '/resources'
    | '/stakeholders'
    | '/understanding'
    | '/understanding/bystander'
    | '/understanding/consent'
    | '/understanding/misconduct'
    | '/understanding/procedures'
    | '/understanding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GlossaryRoute: typeof GlossaryRoute
  QuizRoute: typeof QuizRoute
  ReportingRoute: typeof ReportingRoute
  ResourcesRoute: typeof ResourcesRoute
  StakeholdersRoute: typeof StakeholdersRoute
  UnderstandingRoute: typeof UnderstandingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/understanding': {
      id: '/understanding'
      path: '/understanding'
      fullPath: '/understanding'
      preLoaderRoute: typeof UnderstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholders': {
      id: '/stakeholders'
      path: '/stakeholders'
      fullPath: '/stakeholders'
      preLoaderRoute: typeof StakeholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin': {
      id: '/Admin'
      path: '/Admin'
      fullPath: '/Admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/understanding/': {
      id: '/understanding/'
      path: '/'
      fullPath: '/understanding/'
      preLoaderRoute: typeof UnderstandingIndexRouteImport
      parentRoute: typeof UnderstandingRoute
    }
    '/understanding/procedures': {
      id: '/understanding/procedures'
      path: '/procedures'
      fullPath: '/understanding/procedures'
      preLoaderRoute: typeof UnderstandingProceduresRouteImport
      parentRoute: typeof UnderstandingRoute
    }
    '/understanding/misconduct': {
      id: '/understanding/misconduct'
      path: '/misconduct'
      fullPath: '/understanding/misconduct'
      preLoaderRoute: typeof UnderstandingMisconductRouteImport
      parentRoute: typeof UnderstandingRoute
    }
    '/understanding/consent': {
      id: '/understanding/consent'
      path: '/consent'
      fullPath: '/understanding/consent'
      preLoaderRoute: typeof UnderstandingConsentRouteImport
      parentRoute: typeof UnderstandingRoute
    }
    '/understanding/bystander': {
      id: '/understanding/bystander'
      path: '/bystander'
      fullPath: '/understanding/bystander'
      preLoaderRoute: typeof UnderstandingBystanderRouteImport
      parentRoute: typeof UnderstandingRoute
    }
  }
}

interface UnderstandingRouteChildren {
  UnderstandingBystanderRoute: typeof UnderstandingBystanderRoute
  UnderstandingConsentRoute: typeof UnderstandingConsentRoute
  UnderstandingMisconductRoute: typeof UnderstandingMisconductRoute
  UnderstandingProceduresRoute: typeof UnderstandingProceduresRoute
  UnderstandingIndexRoute: typeof UnderstandingIndexRoute
}

const UnderstandingRouteChildren: UnderstandingRouteChildren = {
  UnderstandingBystanderRoute: UnderstandingBystanderRoute,
  UnderstandingConsentRoute: UnderstandingConsentRoute,
  UnderstandingMisconductRoute: UnderstandingMisconductRoute,
  UnderstandingProceduresRoute: UnderstandingProceduresRoute,
  UnderstandingIndexRoute: UnderstandingIndexRoute,
}

const UnderstandingRouteWithChildren = UnderstandingRoute._addFileChildren(
  UnderstandingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GlossaryRoute: GlossaryRoute,
  QuizRoute: QuizRoute,
  ReportingRoute: ReportingRoute,
  ResourcesRoute: ResourcesRoute,
  StakeholdersRoute: StakeholdersRoute,
  UnderstandingRoute: UnderstandingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
